### ISSUE TITLE
Current attribute assumes next/prev is a string

### ISSUE THREAD

**Issue by nvernooy** [ruyadorno/angular-simple-slider#11]
Want to say thanks for the great work, I just found a minor bug.
The "current-slide" attribute assumes the next/prev parameters are strings. 
And if a 0 (integer) next index is passed to it,
`if (next && next !== prev)` 
evaluates to false.

It took me a while to figure out why the current slide was not working for me when I was using $index inside an ngRepeat. It was easy to fix by casting $index to string, but I think it would be better to change the conditional to something like 
`if (next !== undefined && next !== prev)`

**Comment by DanMMX** [comment]
thanks @nvernooy , do you mind making a PR?

**Comment by nvernooy** [comment]
Sure, if my solution works for you

**Comment by DanMMX** [comment]
Fixed due to PR #12
