### ISSUE TITLE
Update bower and create new version

### ISSUE THREAD

**Issue by DanMMX** [ruyadorno/angular-simple-slider#5]
Bower is still on ~1.0.0 and downloads that version, not the latest master version

**Comment by DanMMX** [comment]
Nvm… was my markup what I needed to update

**Comment by ruyadorno** [comment]
don't worry, it was still useful as a report. I forgot to publish **v1.0.0** to `npm` but this issue made me remember to do that ^^

thanks!

**Comment by DanMMX** [comment]
haha glad I helped on that
